### ISSUE TITLE
Fix: buttons styling

### ISSUE THREAD

**Issue by AnnaSolovykh** [JULIERAJ/KIDS-FIRST-v2#106]
1) Fix the hover of the buttons 
![Image](https://github.com/JULIERAJ/KIDS-FIRST-v2/assets/114008959/35d6e8c7-1d32-41c6-9250-637b27f8de4d)
![Image](https://github.com/JULIERAJ/KIDS-FIRST-v2/assets/114008959/370de207-436f-4249-a0b5-0b9dc158699a)

2) The buttons design should match the figma design 
App:
![Image](https://github.com/JULIERAJ/KIDS-FIRST-v2/assets/114008959/ef2d402d-0da7-42b3-9c94-103e38f49d49)

Figma:
![Image](https://github.com/JULIERAJ/KIDS-FIRST-v2/assets/114008959/9cbda4d4-700a-4fb1-b712-3ffdeb09f2e1)

**Comment by KatePolyakov** [comment]
![Image](https://github.com/JULIERAJ/KIDS-FIRST-v2/assets/72521760/789eb058-5b8c-4713-8b8b-3a52ed476328)
