### ISSUE TITLE
Fix: align account verification layout with Figma

### ISSUE THREAD

**Issue by AnnaSolovykh** [JULIERAJ/KIDS-FIRST-v2#137]
**Requirements**
- Follow the design in Figma in the following pages: Email Verified, Link Expired, Something went wrong
- Add functionality to handle the logic in the flow
[Figma](https://www.figma.com/design/qUBlZE5TIgpqShKTVcSvRo/Kids-First-WITT(Desktop)?node-id=0-1&t=J7tX1aYPuECQ1hVW-0)
![Image](https://github.com/JULIERAJ/KIDS-FIRST-v2/assets/114008959/2ae71a1a-3c4d-403a-9273-17b6eeb8aef1)

![Image](https://github.com/JULIERAJ/KIDS-FIRST-v2/assets/114008959/df99e058-ef3b-4eb7-ab24-cbcdaf45fae3)

![Image](https://github.com/JULIERAJ/KIDS-FIRST-v2/assets/114008959/720e521f-534d-411d-9612-7977719a83a5)

**Comment by AnnaSolovykh** [comment]
@VrushaliHaldankar01 please move to "in progress" if the task is in progress.

**Comment by VrushaliHaldankar01** [comment]
Yes done
