### ISSUE TITLE
Research testing libraries for back and front

### ISSUE THREAD

**Issue by AnnaSolovykh** [JULIERAJ/KIDS-FIRST-v2#142]
Make a research on testing libraries for frontend and backend and present during the meeting

**Comment by ElenaCherpakova** [comment]
**Backend**: 
[playwrigh](https://playwright.dev/docs/api-testing)  - i think great to start using this to test our backend. Plus it's getting popular.
Here is also [Top 9 Libraries](https://betterstack.com/community/guides/testing/best-node-testing-libraries/#2-vitest)

**Frontend**: 

[React Testing Library (RTL)](https://testing-library.com/docs/react-testing-library/example-intro)
[Vitest](https://vitest.dev/)
[Jest](https://jestjs.io/docs/tutorial-react)
